# Generated by Django 2.0.2 on 2018-03-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='lastname_attrs',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
