# Generated by Django 2.0.2 on 2018-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_lastname_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='email_attrs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='fax_attrs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='firstname_attrs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='phone_attrs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='position_attrs',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
